apiVersion: v1
kind: Namespace
metadata:
  name: acbot-backend

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kubernetes-dashboard
  name: flow-orchestration-cm
  namespace: acbot-backend
data:
  application.yml: |+
    spring:
      cloud:
        kubernetes:
          reload:
            enabled: true
      datasource:
        # url: jdbc:postgresql://pgsql-service.pgsql:5432/robots?currentSchema=robots&serverTimezone=UTC&characterEncoding=utf-8
        url: jdbc:postgresql://10.108.114.4:5432/robots?currentSchema=robots&serverTimezone=UTC&characterEncoding=utf-8
        driverClassName: org.postgresql.Driver
        username: admin
        password: 123456
    mybatis:
      mapper-locations: classpath:mapper/*Mapper.xml
    server:
      port: 8080
    management:
      health:
        redis:
          enabled: false

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: floworch-deployment
  namespace: acbot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floworch
  template:
    metadata:
      labels:
        app: floworch
    spec:
      containers:
        - name: floworch-pod
          image: harbor.acbot.net/acbot/backend/flow-orchestration:v0.1.0-alpha.2102051
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /root/config
              name: config
      volumes:
        - name: config
          configMap:
            name: flow-orchestration-cm


---

kind: Service
apiVersion: v1
metadata:
  name: floworch-service
  namespace: acbot-backend
spec:
  type: NodePort
  selector:
    app: floworch
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31616