apiVersion: v1
data:
  iperf-server.yml: |
    kind: DaemonSet
    apiVersion: apps/v1
    metadata:
      name: iperf-server
      namespace: acbot-edge
    spec:
      selector:
        matchLabels:
          app: iperf-server
      template:
        metadata:
          labels:
            app: iperf-server
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          nodeSelector:
            node_type: leaf
          containers:
            - name: iperf-server
              image: networkstatic/iperf3:latest
              imagePullPolicy: IfNotPresent
              args: ["-s"]
              ports:
                - containerPort: 5201
  monitor.yml: |
    kind: DaemonSet
    apiVersion: apps/v1
    metadata:
      name: monitor
      namespace: acbot-edge
    spec:
      selector:
        matchLabels:
          app: monitor
      template:
        metadata:
          labels:
            app: monitor
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          nodeSelector:
            node_type: non-leaf
          containers:
            - name: monitor
              image: 19231149/monitor:latest
              imagePullPolicy: IfNotPresent
              args:
                - '$(NODE_NAME)'
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              ports:
                - containerPort: 5201
              volumeMounts:
                - mountPath: /app/resources
                  name: config
          volumes:
            - name: config
              configMap:
                name: monitor-cm
  profile.toml: |
    info_management_address = "info-management.acbot-backend:8081"
    flowdeploy_backend_address = "flowdeploy-backend.ircp-workflow:80"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"iperf-server.yml":"kind: DaemonSet\napiVersion: apps/v1\nmetadata:\n  name: iperf-server\n  namespace: acbot-edge\nspec:\n  selector:\n    matchLabels:\n      app: iperf-server\n  template:\n    metadata:\n      labels:\n        app: iperf-server\n    spec:\n      hostNetwork: true\n      dnsPolicy: ClusterFirstWithHostNet\n      nodeSelector:\n        node_type: leaf\n      containers:\n        - name: iperf-server\n          image: networkstatic/iperf3:latest\n          imagePullPolicy: IfNotPresent\n          args: [\"-s\"]\n          ports:\n            - containerPort: 5201\n","monitor.yml":"kind: DaemonSet\napiVersion: apps/v1\nmetadata:\n  name: monitor\n  namespace: acbot-edge\nspec:\n  selector:\n    matchLabels:\n      app: monitor\n  template:\n    metadata:\n      labels:\n        app: monitor\n    spec:\n      hostNetwork: true\n      dnsPolicy: ClusterFirstWithHostNet\n      nodeSelector:\n        node_type: non-leaf\n      containers:\n        - name: monitor\n          image: 19231149/monitor:latest\n          imagePullPolicy: IfNotPresent\n          args:\n            - '$(NODE_NAME)'\n          env:\n            - name: NODE_NAME\n              valueFrom:\n                fieldRef:\n                  fieldPath: spec.nodeName\n          ports:\n            - containerPort: 5201\n          volumeMounts:\n            - mountPath: /app/resources\n              name: config\n      volumes:\n        - name: config\n          configMap:\n            name: monitor-cm\n","profile.toml":"info_management_address = \"info-management.acbot-backend:8081\"\nflowdeploy_backend_address = \"flowdeploy-backend.ircp-workflow:80\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"dispatcher-cm","namespace":"acbot-edge"}}
  creationTimestamp: "2023-03-21T01:14:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:iperf-server.yml: {}
        f:monitor.yml: {}
        f:profile.toml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-03-21T02:57:59Z"
  name: dispatcher-cm
  namespace: acbot-edge
  resourceVersion: "128868"
  uid: 0cb7b1df-7da8-4111-9df6-c71a7babd535
